name: Cypress automated testing for The Agricultural Trust
on: [push]
jobs:
  cypress-run:
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
        start: npm start
